### ISSUE TITLE
Project Pane Contents Do Not Change After Adding a Project

### ISSUE THREAD

**Issue by jmwright** [Stemn/Stemn-Desktop#18]
After adding a project (doesn't seem to matter if it's public or private), clicking between projects in the "My Projects" list changes the project pane toolbar (Changes/History/Threads/Files/icons/name), but doesn't change the project pane's contents. Clicking on the project pane's buttons has not effect, none of the content changes.

**Comment by sabrehagen** [comment]
This is indicative of corrupt data causing the app to crash. Changing projects after the app is in this state will cause them not to load as you have described. So we can find out exactly the data that is corrupt, can you please restart the app, go to Application Settings, and turn on the Debug Mode option. Then can you please change projects again and post a screenshot of the error that shows in the console? Thanks!

**Comment by jmwright** [comment]
I don't get any error, even after enabling Debug Mode. Is there a console that I should be opening or something?

**Comment by sabrehagen** [comment]
Hmm, on Ubuntu 16.04 the console does not seem to open automatically once debug mode is enabled. Pressing Ctrl+Shift+i will open the console manually.

**Comment by jmwright** [comment]
Here's the log that starts with me clicking between files, then adding a project, then clicking between files again.

[stemn_desktop_ubuntu_160_04.log.zip](https://github.com/stemn/Stemn-Desktop/files/1222304/stemn_desktop_ubuntu_160_04.log.zip)

**Comment by sabrehagen** [comment]
Thanks for the log. Unfortunately it isn't showing anything we can use to debug this one. Can you try removing the `~/.config/Stemn/state.json` file? This will log you out and clear your application state. Afterwards please retry changing projects and see if the issue persists.

If removing `state.json` resolves the issue, there was a data incompatibility between different versions of the app state file that causes it to crash. If not, we'll have to debug further.

**Comment by jmwright** [comment]
Deleting state.json didn't fix the problem.

These getHostNode errors and 401 error aren't the cause?

```
vendor.js:12 Uncaught (in promise) TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (vendor.js:12)
    at h.getHostNode (vendor.js:40)
    at Object.getHostNode (vendor.js:12)
    at Object.updateChildren (vendor.js:39)
    at _reconcilerUpdateChildren (vendor.js:41)
    at _updateChildren (vendor.js:41)
    at _.updateChildren (vendor.js:41)
    at _updateDOMChildren (vendor.js:40)
    at _.updateComponent (vendor.js:40)
    at _.receiveComponent (vendor.js:40)
    at Object.receiveComponent (vendor.js:12)
    at Object.updateChildren (vendor.js:39)
    at _reconcilerUpdateChildren (vendor.js:41)
    at _updateChildren (vendor.js:41)
    at _.updateChildren (vendor.js:41)
    at _updateDOMChildren (vendor.js:40)
    at _.updateComponent (vendor.js:40)
    at _.receiveComponent (vendor.js:40)
    at Object.receiveComponent (vendor.js:12)
    at h._updateRenderedComponent (vendor.js:40)
    at h._performComponentUpdate (vendor.js:40)
    at h.updateComponent (vendor.js:40)
    at h.receiveComponent (vendor.js:40)
    at Object.receiveComponent (vendor.js:12)
    at h._updateRenderedComponent (vendor.js:40)
    at h._performComponentUpdate (vendor.js:40)
    at h.updateComponent (vendor.js:40)
    at h.receiveComponent (vendor.js:40)
    at Object.receiveComponent (vendor.js:12)
    at Object.updateChildren (vendor.js:39)
    at _reconcilerUpdateChildren (vendor.js:41)
    at _updateChildren (vendor.js:41)
    at _.updateChildren (vendor.js:41)
    at _updateDOMChildren (vendor.js:40)
    at _.updateComponent (vendor.js:40)
    at _.receiveComponent (vendor.js:40)
    at Object.receiveComponent (vendor.js:12)
    at Object.updateChildren (vendor.js:39)
    at _reconcilerUpdateChildren (vendor.js:41)
    at _updateChildren (vendor.js:41)
    at _.updateChildren (vendor.js:41)
    at _updateDOMChildren (vendor.js:40)
    at _.updateComponent (vendor.js:40)
    at _.receiveComponent (vendor.js:40)
    at Object.receiveComponent (vendor.js:12)
    at h._updateRenderedComponent (vendor.js:40)
    at h._performComponentUpdate (vendor.js:40)
    at h.updateComponent (vendor.js:40)
    at h.receiveComponent (vendor.js:40)
    at Object.receiveComponent (vendor.js:12)
vendor.js:38 Uncaught TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (vendor.js:12)
    at h.getHostNode (vendor.js:40)
    at Object.getHostNode (vendor.js:12)
    at Object.updateChildren (vendor.js:39)
    at _reconcilerUpdateChildren (vendor.js:41)
    at _updateChildren (vendor.js:41)
    at _.updateChildren (vendor.js:41)
    at _updateDOMChildren (vendor.js:40)
    at _.updateComponent (vendor.js:40)
    at _.receiveComponent (vendor.js:40)
    at Object.receiveComponent (vendor.js:12)
    at Object.updateChildren (vendor.js:39)
    at _reconcilerUpdateChildren (vendor.js:41)
    at _updateChildren (vendor.js:41)
    at _.updateChildren (vendor.js:41)
    at _updateDOMChildren (vendor.js:40)
    at _.updateComponent (vendor.js:40)
    at _.receiveComponent (vendor.js:40)
    at Object.receiveComponent (vendor.js:12)
    at h._updateRenderedComponent (vendor.js:40)
    at h._performComponentUpdate (vendor.js:40)
    at h.updateComponent (vendor.js:40)
    at h.receiveComponent (vendor.js:40)
    at Object.receiveComponent (vendor.js:12)
    at h._updateRenderedComponent (vendor.js:40)
    at h._performComponentUpdate (vendor.js:40)
    at h.updateComponent (vendor.js:40)
    at h.receiveComponent (vendor.js:40)
    at Object.receiveComponent (vendor.js:12)
    at Object.updateChildren (vendor.js:39)
    at _reconcilerUpdateChildren (vendor.js:41)
    at _updateChildren (vendor.js:41)
    at _.updateChildren (vendor.js:41)
    at _updateDOMChildren (vendor.js:40)
    at _.updateComponent (vendor.js:40)
    at _.receiveComponent (vendor.js:40)
    at Object.receiveComponent (vendor.js:12)
    at Object.updateChildren (vendor.js:39)
    at _reconcilerUpdateChildren (vendor.js:41)
    at _updateChildren (vendor.js:41)
    at _.updateChildren (vendor.js:41)
    at _updateDOMChildren (vendor.js:40)
    at _.updateComponent (vendor.js:40)
    at _.receiveComponent (vendor.js:40)
    at Object.receiveComponent (vendor.js:12)
    at h._updateRenderedComponent (vendor.js:40)
    at h._performComponentUpdate (vendor.js:40)
    at h.updateComponent (vendor.js:40)
    at h.receiveComponent (vendor.js:40)
    at Object.receiveComponent (vendor.js:12)
http://35.167.249.144:9000/api/2/store/?sentry_version=7&sentry_client=raven-js%2F3.15.0&sentry_key=fae90f76026746ecbb42464ba51ec2ec Failed to load resource: the server responded with a status of 401 (UNAUTHORIZED)
```

**Comment by sabrehagen** [comment]
The 401 is related to the error not being accepted by our error logging server (we need to reconfigure the error server auth for the next release). @MrBlenny will be online in 10 hours and he can report on the `getHostNode` error - I'm not experienced with this one.

**Comment by jmwright** [comment]
Not sure if this is related, but I was looking at the application log in ~/.config and noticed this.

```
[2017-08-14 09:00:51:0208] [info] ---------------- Application started ----------------
[2017-08-14 09:00:51:0720] [info] argv [ '/tmp/.mount_qfmvP6/usr/bin/stemn' ]
[2017-08-14 09:00:51:0726] [info] Start flags: { mode: { hidden: false }, inputs: { path: undefined } }
[2017-08-14 09:00:51:0756] [error] Invalid state store: Error: Invalid data
    at /tmp/.mount_qfmvP6/usr/bin/resources/app.asar/main/index.js:16688:25
    at nextTask (/tmp/.mount_qfmvP6/usr/bin/resources/app.asar/main/index.js:53063:14)
    at next (/tmp/.mount_qfmvP6/usr/bin/resources/app.asar/main/index.js:53070:9)
    at /tmp/.mount_qfmvP6/usr/bin/resources/app.asar/main/index.js:48696:16
    at /tmp/.mount_qfmvP6/usr/bin/resources/app.asar/main/index.js:16673:18
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)

[2017-08-14 09:00:51:0774] [info] Provider Path Dropbox
[2017-08-14 09:00:57:0156] [info] Current version: 0.0.25
[2017-08-14 09:00:57:0246] [info] Update for linux-x64-prod-v0.0.25 is not available
```

That would have been before I deleted the state.json file, and I don't see the error after that point. The original problem does still persist though.

**Comment by MrBlenny** [comment]
Yes, the `Cannot read property 'getHostNode'` error will only appear after another error.
Maybe you could send through a screenshot of the console window? The actual error is usually just a few items before the 'getHostNode' error. It is sometimes hidden inside a `XXXX/XXX_XXX_REJECTED` console log.

**Comment by jmwright** [comment]
After I create the project I get this:
![screenshot_2017-08-15_10-42-36](https://user-images.githubusercontent.com/1015439/29320878-a8d68a1c-81a6-11e7-8598-a764880283e0.png)

After I try to click over to another project I see this:
![screenshot_2017-08-15_10-44-42](https://user-images.githubusercontent.com/1015439/29320913-c6b02f0c-81a6-11e7-8037-ace924da506f.png)

If I search the log for "REJECTED" I don't see any results.

**Comment by sabrehagen** [comment]
When you enable debug mode in settings, you will see events of this form in the console. If you expand the action ending with `REJECTED` then click `payload`, then `data`, you will see the response from the API. 

![events](https://user-images.githubusercontent.com/1094600/29322785-1d18ff6a-8222-11e7-9aeb-3a4fc1df63ee.png)

**Comment by jmwright** [comment]
I don't see data under payload.

![screenshot_2017-08-15_11-42-03](https://user-images.githubusercontent.com/1015439/29323409-d0fb4eda-81ae-11e7-9e90-a054fe553bdf.png)

There's also an issue with debugging mode. After I enable it, I get 1 restart and then I get kicked out and have to log in again. When I log in, my projects listing is incorrect. If I restart the desktop app everything goes back to normal, but debugging has been turned off again.

**Comment by sabrehagen** [comment]
`SHOW_MODAL_REJECTED` is typically an expected rejection. Are there any
other instances of `REJECTED` events?

**Comment by jmwright** [comment]
Not that I see, just that one.

[stemn_debug_2017-08-15_1.log.zip](https://github.com/stemn/Stemn-Desktop/files/1225612/stemn_debug_2017-08-15_1.log.zip)

**Comment by jmwright** [comment]
I circled back to this a bit ago to try again and still don't see any *REJECTED actions in the debug logs, even after clicking around. Lots of other actions, but no rejected ones.
